# Generated by Django 4.2.4 on 2023-08-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankAPI', '0002_remove_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankAPI.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='accountID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankAPI.account'),
        ),
    ]
