# Generated by Django 4.2.4 on 2023-08-04 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankAPI', '0004_remove_account_iduser_remove_card_idaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountSpent', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankAPI.card')),
            ],
        ),
    ]
